 default: &default
   adapter: postgresql
   encoding: unicode
   pool: 5

 development:
   <<: *default
   database: after20_development
   username: postgres
   password: postgres

 test:
   <<: *default
   database: after20_test
   username: postgres
   password: postgres

 production:
   <<: *default
   database: after20_production
   username: postgres
   password: postgres
