# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bde698907984efa304f2cc2c192fc6b7c7e328836a5789c39be045cd69b7965f50db6cc1100758a367aaa4e8381365bf4fcf930fdca9f962baa8b593ef6b4a6

test:
  secret_key_base: db43232213cbf5703e8e953fed93cc00fff1a4028671a5288cc7c12aa9b12ba5b5616a10c1cd23b50c8d84e6a051ff6c8f6912a2b3b3bd4b88c5fcaeae1cf5ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
